export const MENU_MANAGER_TYPES = {
  TOGGLE_CART : "TOGGLE_CART",
  TOGGLE_BURGER_MENU : "TOGGLE_BURGER_MENU",
  TOGGLE_FILTER_PRODUCT: "TOGGLE_FILTER_PRODUCT"
};

export const CART_TYPES = {
  ADD_PRODUCT_TO_CART : "ADD_PRODUCT_TO_CART",
};

export const FILTER_PRODUCTS_TYPES = {
  FILTER_PRODUCTS : "FILTER_PRODUCTS",
  SET_FILTER_PARAMETERS: "SET_FILTER_PARAMETERS",
  RESET_FILTER_PRODUCTS: "RESET_FILTER_PRODUCTS",
};