export const MENU_MANAGER_TYPES = {
  TOGGLE_CART : "TOGGLE_CART",
  TOGGLE_BURGER_MENU : "TOGGLE_BURGER_MENU",
  TOGGLE_FILTER_PRODUCT: "TOGGLE_FILTER_PRODUCT"
}

export const CART_TYPES = {
  ADD_PRODUCT_TO_CART : "ADD_PRODUCT_TO_CART",
}